### ISSUE TITLE
PART without any params will cause ZNC failure...

### ISSUE THREAD

**Issue by cs8898** [MCMrARM/chatlib#1]
When i send a /part from revolution-IRC i get a ZNC failure...
I thing this is because of following codeline

https://github.com/MCMrARM/chatlib/blob/70df9ee25a813b000f79061e49367c6083b78e38/chatlib/src/main/java/io/mrarm/chatlib/irc/IRCConnection.java#L72

```
[2018-02-21 17:46:54.345360] (cs8898/NET) ZNC -> IRC [PART #masterbot :]
[2018-02-21 17:46:54.356122] (christian.schmied/NET) IRC -> ZNC [@time=2018-02-21T22:46:54.350Z :cs8898!~cs8898@world.tld PART #masterbot]
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
Aborted
```

I think the ":" is wrong at this spot, ther shouldnt be any more chars just a solid ```PART #masterbot```

Probably im wrong, and this is caused inside the App...

**Comment by cs8898** [comment]
Seems like you dont really use this block in your android App...

I think i now really found it, but will first trie a fork ;D

**Comment by MCMrARM** [comment]
Hello, the /part command is handled by the command system. The PART command is defined as `PART ${channel} :${message}`. The empty leave message imo should be ignored by ZNC.

**Comment by MCMrARM** [comment]
I guess a second `/part` definition would be needed to fix this.
