### ISSUE TITLE
Stucking in Connecting when using recent ZNC and block_motd

### ISSUE THREAD

**Issue by glguy** [MCMrARM/chatlib#3]
When there's no MOTD, `ERR_NOMOTD` (422) is sent. This could also trigger the transition from _Connecting_ to _Connected_. When I connected to a ZNC server using the `block_motd`plugin, the library never realizes that the connection is complete.

For what it's worth in my client I use the `001` welcome message as indication of successful registration and considering the connection established.

**Comment by MCMrARM** [comment]
I decided to use the MOTD one as HexChat does it this way. I guess I'll need to investigate more.
I'd expect the ERR_NOMOTD to be sent though, welp.

**Comment by glguy** [comment]
I think using MOTD makes sense; I was just thinking you could _also_ accept `422` as a way to indicate the connection was established.

**Comment by MCMrARM** [comment]
422 should mark the connection as established, does it not?

Or do you mean using 001?

**Comment by glguy** [comment]
`422` doesn't mark it connected in the Google Play version of Revolution IRC, which I understand uses this library for IRC protocol logic. It's possible this has been fixed since the client was released to the Play store.

I see that there is already code for handling 422 in chatlib, so I suppose I just need to wait for a new release.

The other possibility is that znc stopped sending 422 in a recent version. I'll check and close this ticket if that's what changed!

**Comment by glguy** [comment]
OK, so the problem is that current versions of ZNC using `block_motd` stopped sending `422` and now they send only `376` as the sole MOTD reply.

```
:tolkien.freenode.net 001 glguy :Welcome to the freenode Internet Relay Chat Network glguy
:tolkien.freenode.net 002 glguy :Your host is tolkien.freenode.net[71.11.84.232/6697], running version ircd-seven-1.1.4
:tolkien.freenode.net 003 glguy :This server was created Thu May 18 2017 at 17:43:36 UTC
:tolkien.freenode.net 004 glguy tolkien.freenode.net ircd-seven-1.1.4 DOQRSZaghilopswz CFILMPQSbcefgijklmnopqrstvz bkloveqjfI
:tolkien.freenode.net 005 glguy CHANTYPES=# EXCEPTS INVEX CHANMODES=eIbq,k,flj,CFLMPQScgimnprstz CHANLIMIT=#:120 PREFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=freenode STATUSMSG=@+ CALLERID=g CASEMAPPING=rfc1459 :are supported by this server
:tolkien.freenode.net 005 glguy CHARSET=ascii NICKLEN=16 CHANNELLEN=50 TOPICLEN=390 DEAF=D FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: EXTBAN=$,ajrxz CLIENTVER=3.0 KNOCK WHOX ETRACE :are supported by this server
:tolkien.freenode.net 005 glguy CPRIVMSG CNOTICE SAFELIST ELIST=CTU :are supported by this server
:tolkien.freenode.net 251 glguy :There are 126 users and 92952 invisible on 34 servers
:tolkien.freenode.net 252 glguy 27 :IRC Operators online
:tolkien.freenode.net 254 glguy 51018 :channels formed
:tolkien.freenode.net 255 glguy :I have 4797 clients and 1 servers
:tolkien.freenode.net 265 glguy 4797 7644 :Current local users 4797, max 7644
:tolkien.freenode.net 266 glguy 93078 97718 :Current global users 93078, max 97718
:tolkien.freenode.net 250 glguy :Highest connection count: 7645 (7644 clients) (4524051 connections received)
:tolkien.freenode.net 376 glguy :MOTD blocked by ZNC
:glguy!~glguy@haskell/developer/glguy MODE glguy :+RZi
```

I believe that the issue is actually that chatlib (reasonably) demands that `RPL_ENDOFMOTD` happens *after* `RPL_MOTDSTART` or it considers the message invalid.

https://github.com/MCMrARM/chatlib/blob/70df9ee25a813b000f79061e49367c6083b78e38/chatlib/src/main/java/io/mrarm/chatlib/irc/handlers/MotdCommandHandler.java#L43

So ZNC's acting weird and maybe this isn't something you're worried about supporting, or maybe you could allow a lone `RPL_ENDOFMOTD` to complete the connecting process.

**Comment by MCMrARM** [comment]
I see, thanks, will fix it.

**Comment by glguy** [comment]
Thanks!
