### ISSUE TITLE
IRC messages should end in CR LF

### ISSUE THREAD

**Issue by michaelforney** [MCMrARM/chatlib#4]
RFC 1459 says

> IRC messages are always lines of characters terminated with a CR-LF (Carriage Return - Line Feed) pair

It looks like chatlib is just sending LF. I noticed this when trying to use RevolutionIRC to connect to a server which expects CR LF as the separator, so the connection just hung.

**Comment by gjabell** [comment]
Any movement on this issue? Using RevolutionIRC with [pounce](https://git.causal.agency/pounce/) exhibits the same "connection hang" problem.
